config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :products
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root 'home#index'
  get '/forms', to: 'home#forms'
  get '/users', to: 'home#users'
  get '/modals', to: 'home#modals'
  get '/signin', to: 'home#signin'
  get '/signup', to: 'home#signup'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :products

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "updated_at"]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name, :quantity, :price
  validates :name, uniqueness: true
  belongs_to :category

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "id", "id_value", "name", "price", "quantity", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["category"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to category_url(@category), notice: "Category was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @category.update(category_params)
      redirect_to category_url(@category), notice: "Category was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy!

    redirect_to categories_url, notice: "Category was successfully destroyed."
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: %i[show edit update destroy]
  before_action :set_categories, only: %i[new create edit update]

  def index
    @q = Product.includes(:category).order(name: :asc).ransack(params[:q])
    @products = @q.result(distinct: true).page(params[:page]).per(100)
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to product_url(@product), notice: "Product was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @product.update(product_params)
      redirect_to product_url(@product), notice: "Product was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy!

    redirect_to products_url, notice: "Product was successfully destroyed."
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def set_categories
      @categories = Category.all
    end

    def product_params
      params.require(:product).permit(:name, :category_id, :quantity, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_category.html.erb
<div class="flex flex-col justify-center my-auto pb-6 px-4 text-gray-700 border border-gray-200 rounded-lg bg-gray-50 dark:bg-gray-800 dark:border-gray-600">
  <%= form_for(category, url: '#', html: { class: 'space-y-2 md:space-y-4' }) do |f| %>
    <div class="field">
      <%= f.label :name, class: 'block mb-2 text-gray-900 dark:text-white' %>
      <%= f.text_field :name, autofocus: true, autocomplete: 'off', class: 'bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', disabled: true %>
    </div>

    <div class="actions w-full">
      <%= link_to 'Edit Category', edit_category_path(category), class: 'mt-2 w-full flex justify-center text-center px-4 py-2 font-medium text-green-800 bg-transparent border rounded-lg border-green-800 hover:bg-green-800 hover:text-white dark:border-green-500 dark:text-green-500 dark:hover:text-white dark:hover:bg-green-700 dark:focus:bg-green-700' %>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<!-- Breadcrumb -->
<%= render partial: '/layouts/components/breadcrumb', locals: { url_data: [{ page_link: root_path, page_name: 'Home' }, { page_link: categories_path, page_name: 'Categories' }], current_page: 'Edit' } %>

<div class='my-4'></div>

<%= render "form", category: @category %>

app/views/categories/index.html.erb
<!-- Breadcrumb -->
<%= render partial: '/layouts/components/breadcrumb', locals: { url_data: [{ page_link: root_path, page_name: 'Home' }, { page_link: categories_path, page_name: 'Categories' }], current_page: 'Index' } %>

<div class='flex justify-between space-x-2 my-4'>
  <div>
    <form>
      <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only dark:text-white">Search</label>
      <div class="relative">
        <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
          <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
          </svg>
        </div>
        <input type="search" id="default-search" class="block w-full ps-10 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search" required>
      </div>
    </form>
  </div>
  <div>
    <%= link_to 'New', new_category_path, class: 'inline-flex items-center px-4 py-2 font-medium text-blue-800 bg-transparent border rounded-lg border-blue-800 hover:bg-blue-800 hover:text-white focus:z-10 focus:ring-2 focus:ring-blue-500 focus:bg-blue-800 focus:text-white dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-700 dark:focus:bg-blue-700' %>
  </div>
</div>

<div class="relative overflow-x-auto border dark:border-gray-600 rounded-lg">
  <table class="w-full text-left rtl:text-right text-gray-500 dark:text-gray-400">
    <thead class="text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th scope="col" class="px-6 py-3">
          ID
        </th>
        <th scope="col" class="px-6 py-3">
          Name
        </th>
        <th scope="col" class="px-6 py-3">
          Created at
        </th>
        <th scope="col" class="px-6 py-3">
          Updated at
        </th>
        <th scope="col" class="px-6 py-3 text-center">
          Action
        </th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
          <td class="px-6 py-4 font-medium">
            <%= category.id %>
          </td>
          <td class="px-6 py-4">
            <%= category.name %>
          </td>
          <td class="px-6 py-4">
            <%= category.created_at %>
          </td>
          <td class="px-6 py-4">
            <%= category.updated_at %>
          </td>
          <td class="px-6 py-4 flex justify-center">
            <div class="inline-flex space-x-2">
              <%= link_to 'Show', category_path(category), class: 'inline-flex items-center px-4 py-2 font-medium text-blue-800 bg-transparent border rounded-lg border-blue-800 hover:bg-blue-800 hover:text-white focus:z-10 focus:ring-2 focus:ring-blue-500 focus:bg-blue-800 focus:text-white dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-700 dark:focus:bg-blue-700' %>
              <%= link_to 'Edit', edit_category_path(category), class: 'inline-flex items-center px-4 py-2 font-medium text-green-800 bg-transparent border rounded-lg border-green-800 hover:bg-green-800 hover:text-white focus:z-10 focus:ring-2 focus:ring-green-500 focus:bg-green-800 focus:text-white dark:border-green-500 dark:text-green-500 dark:hover:text-white dark:hover:bg-green-700 dark:focus:bg-green-700' %>
              <%= link_to 'Delete', category_path(category), data: { "turbo-method": :delete, confirm: 'Are you sure!' }, class: 'inline-flex items-center px-4 py-2 font-medium text-red-800 bg-transparent border rounded-lg border-red-800 hover:bg-red-800 hover:text-white focus:z-10 focus:ring-2 focus:ring-red-500 focus:bg-red-800 focus:text-white dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-700 dark:focus:bg-red-700' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<!-- Breadcrumb -->
<%= render partial: '/layouts/components/breadcrumb', locals: { url_data: [{ page_link: root_path, page_name: 'Home' }, { page_link: categories_path, page_name: 'Categories' }], current_page: 'New' } %>

<div class='my-4'></div>

<%= render "form", category: @category %>

app/views/categories/show.html.erb
<!-- Breadcrumb -->
<%= render partial: '/layouts/components/breadcrumb', locals: { url_data: [{ page_link: root_path, page_name: 'Home' }, { page_link: categories_path, page_name: 'Categories' }], current_page: 'Show' } %>

<div class='my-4'></div>

<%= render @category %>

app/views/layouts/_sidebar.html.erb
<aside id="logo-sidebar" class="fixed top-0 left-0 z-40 w-64 h-screen pt-20 transition-transform -translate-x-full bg-white border-r border-gray-200 sm:translate-x-0 dark:bg-gray-800 dark:border-gray-700" aria-label="Sidebar">
  <div class="h-full px-3 pb-4 overflow-y-auto bg-white dark:bg-gray-800">
    <ul class="space-y-2 font-medium">
      <li>
        <a href="<%= root_path %>" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
          <svg class="w-5 h-5" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <circle cx="12" cy="13" r="2" />  <line x1="13.45" y1="11.55" x2="15.5" y2="9.5" />  <path d="M6.4 20a9 9 0 1 1 11.2 0Z" /></svg>
          <span class="ms-3">Dashboard</span>
        </a>
      </li>
      <li>
        <a href="<%= users_path %>" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
          <svg class="flex-shrink-0 w-5 h-5" viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2" />  <circle cx="9" cy="7" r="4" />  <path d="M23 21v-2a4 4 0 0 0-3-3.87" />  <path d="M16 3.13a4 4 0 0 1 0 7.75" /></svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Users</span>
        </a>
      </li>
      <li>
        <a href="<%= categories_path %>" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
          <svg class="flex-shrink-0 w-5 h-5" viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z" />  <line x1="3" y1="6" x2="21" y2="6" />  <path d="M16 10a4 4 0 0 1-8 0" /></svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Categories</span>
        </a>
      </li>
      <li>
        <a href="<%= products_path %>" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
          <svg class="flex-shrink-0 w-5 h-5" viewBox="0 0 24 24"  fill="none"  stroke="currentColor"  stroke-width="2"  stroke-linecap="round"  stroke-linejoin="round">  <path d="M6 2L3 6v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V6l-3-4z" />  <line x1="3" y1="6" x2="21" y2="6" />  <path d="M16 10a4 4 0 0 1-8 0" /></svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Products</span>
        </a>
      </li>
      <li>
        <a href="<%= modals_path %>" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
          <svg class="flex-shrink-0 w-5 h-5" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z"/><rect x="8" y="4" width="12" height="12" rx="2" /><path d="M16 16v2a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2v-8a2 2 0 0 1 2 -2h2" />
          </svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Modals</span>
        </a>
      </li>
      <li>
      <li>
        <a href="<%= forms_path %>" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
          <svg class="flex-shrink-0 w-5 h-5" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z"/>  <path d="M9 5H7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2V7a2 2 0 0 0 -2 -2h-2" />  <rect x="9" y="3" width="6" height="4" rx="2" />  <line x1="9" y1="12" x2="9.01" y2="12" />  <line x1="13" y1="12" x2="15" y2="12" />  <line x1="9" y1="16" x2="9.01" y2="16" />  <line x1="13" y1="16" x2="15" y2="16" />
          </svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Forms</span>
        </a>
      </li>
      <li>
        <a href="<%= signin_path %>" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
          <svg class="flex-shrink-0 w-5 h-5" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <path d="M14 8v-2a2 2 0 0 0 -2 -2h-7a2 2 0 0 0 -2 2v12a2 2 0 0 0 2 2h7a2 2 0 0 0 2 -2v-2" />  <path d="M20 12h-13l3 -3m0 6l-3 -3" /></svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Sign In</span>
        </a>
      </li>
      <li>
        <a href="<%= signup_path %>" class="flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group">
          <svg class="flex-shrink-0 w-5 h-5" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">  <path stroke="none" d="M0 0h24v24H0z"/>  <circle cx="9" cy="7" r="4" />  <path d="M3 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2" />  <path d="M16 11h6m-3 -3v6" /></svg>
          <span class="flex-1 ms-3 whitespace-nowrap">Sign Up</span>
        </a>
      </li>
    </ul>
  </div>
</aside>

app/views/products/_product.html.erb
<div class="flex flex-col justify-center my-auto pb-6 px-4 text-gray-700 border border-gray-200 rounded-lg bg-gray-50 dark:bg-gray-800 dark:border-gray-600">
  <%= form_for(product, url: '#', html: { class: 'space-y-2 md:space-y-4' }) do |f| %>
    <div class="field">
      <%= f.label :name, class: 'block mb-2 text-gray-900 dark:text-white' %>
      <%= f.text_field :name, autofocus: true, autocomplete: 'off', class: 'bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', disabled: true %>
    </div>

    <div class="field">
      <%= f.label :category_id, class: 'block mb-2 text-gray-900 dark:text-white' %>
      <%= f.text_field :category_id, value: product.category.name, autocomplete: 'off', class: 'bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', disabled: true %>
    </div>

    <div class='flex space-x-2'>
      <div class="field w-1/2">
        <%= f.label :quantity, class: 'block mb-2 text-gray-900 dark:text-white' %>
        <%= f.number_field :quantity, autocomplete: 'off', class: 'bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', disabled: true %>
      </div>

      <div class="field w-1/2">
        <%= f.label :price, class: 'block mb-2 text-gray-900 dark:text-white' %>
        <%= f.number_field :price, autocomplete: 'off', class: 'bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500', disabled: true %>
      </div>
    </div>

    <div class="actions w-full">
      <%= link_to 'Edit Product', edit_product_path(product), class: 'mt-2 w-full flex justify-center text-center px-4 py-2 font-medium text-green-800 bg-transparent border rounded-lg border-green-800 hover:bg-green-800 hover:text-white dark:border-green-500 dark:text-green-500 dark:hover:text-white dark:hover:bg-green-700 dark:focus:bg-green-700' %>
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<!-- Breadcrumb -->
<%= render partial: '/layouts/components/breadcrumb', locals: { url_data: [{ page_link: root_path, page_name: 'Home' }, { page_link: products_path, page_name: 'Products' }], current_page: 'Edit' } %>

<div class='my-4'></div>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<%= render partial: '/layouts/components/breadcrumb', locals: { url_data: [{ page_link: root_path, page_name: 'Home' }, { page_link: products_path, page_name: 'Products' }], current_page: 'Index' } %>

<div class='flex justify-between space-x-2 my-4'>
  <%= search_form_for(@q, url: products_path, html: { class: 'flex space-x-2' }) do |f| %>
    <div class="relative">
      <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
        <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
        </svg>
      </div>
      <%= f.search_field :name_cont, onchange: "$(this).closest('form').submit();", placeholder: 'Search Product Name', class: 'block w-full ps-10 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' %>
    </div>

    <div class="relative">
      <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
        <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
        </svg>
      </div>
      <%= f.search_field :category_name_cont, onchange: "$(this).closest('form').submit();", placeholder: 'Search Category Name', class: 'block w-full ps-10 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500' %>
    </div>
  <% end %>
  <div>
    <%= link_to 'New', new_product_path, class: 'inline-flex items-center px-4 py-2 font-medium text-blue-800 bg-transparent border rounded-lg border-blue-800 hover:bg-blue-800 hover:text-white focus:z-10 focus:ring-2 focus:ring-blue-500 focus:bg-blue-800 focus:text-white dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-700 dark:focus:bg-blue-700' %>
  </div>
</div>

<div class="relative overflow-x-auto border dark:border-gray-600 rounded-lg">
  <table class="w-full text-left rtl:text-right text-gray-500 dark:text-gray-400">
    <thead class="text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr>
        <th class="px-6 py-3"><%= sort_link(@q, :id, 'ID') %></th>
        <th class="px-6 py-3"><%= sort_link(@q, :name, 'name') %></th>
        <th class="px-6 py-3"><%#= sort_link(@q, :category_name, 'category') %>category</th>
        <th class="px-6 py-3"><%= sort_link(@q, :quantity, 'quantity') %></th>
        <th class="px-6 py-3"><%= sort_link(@q, :price, 'price') %></th>
        <th class="px-6 py-3"><%= sort_link(@q, :created_at, 'created at') %></th>
        <th class="px-6 py-3"><%= sort_link(@q, :updated_at, 'updated at') %></th>
        <th class="px-6 py-3 text-center">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
          <td class="px-6 py-2"><%= product.id %></td>
          <td class="px-6 py-2 truncate max-w-64"><%= highlight product.name, params.dig(:q, :name_cont) %></td>
          <td class="px-6 py-2 truncate max-w-64"><%= highlight product.category.name, params.dig(:q, :category_name_cont) %></td>
          <td class="px-6 py-2"><%= product.quantity %></td>
          <td class="px-6 py-2"><%= product.price %></td>
          <td class="px-6 py-2"><%= product.created_at.strftime('%a, %b %d %Y %I:%M %p') %></td>
          <td class="px-6 py-2"><%= product.updated_at.strftime('%a, %b %d %Y %I:%M %p') %></td>
          <td class="px-6 py-2 flex justify-center">
            <div class="inline-flex space-x-2">
              <%= link_to 'Show', product_path(product), class: 'inline-flex items-center px-2 py-1 font-medium text-blue-800 bg-transparent border rounded-lg border-blue-800 hover:bg-blue-800 hover:text-white focus:z-10 focus:ring-2 focus:ring-blue-500 focus:bg-blue-800 focus:text-white dark:border-blue-500 dark:text-blue-500 dark:hover:text-white dark:hover:bg-blue-700 dark:focus:bg-blue-700' %>
              <%= link_to 'Edit', edit_product_path(product), class: 'inline-flex items-center px-2 py-1 font-medium text-green-800 bg-transparent border rounded-lg border-green-800 hover:bg-green-800 hover:text-white focus:z-10 focus:ring-2 focus:ring-green-500 focus:bg-green-800 focus:text-white dark:border-green-500 dark:text-green-500 dark:hover:text-white dark:hover:bg-green-700 dark:focus:bg-green-700' %>
              <%= link_to 'Delete', product_path(product), data: { "turbo-method": :delete, confirm: 'Are you sure!' }, class: 'inline-flex items-center px-2 py-1 font-medium text-red-800 bg-transparent border rounded-lg border-red-800 hover:bg-red-800 hover:text-white focus:z-10 focus:ring-2 focus:ring-red-500 focus:bg-red-800 focus:text-white dark:border-red-500 dark:text-red-500 dark:hover:text-white dark:hover:bg-red-700 dark:focus:bg-red-700' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class='my-2 px-2 py-2 flex sm:flex-wrap-reverse xs:flex-wrap-reverse lg:justify-between md:justify-center sm:justify-center xs:justify-center border rounded-lg text-gray-700 border-gray-200 dark:border-gray-600'>
  <div class="pagination justify-center">
    <%= paginate @products  %>
  </div>
  <div class='max-w-max px-2 py-2 my-2 text-base border rounded-lg text-gray-700 border-gray-200 bg-gray-50 dark:text-gray-200 dark:bg-gray-800 dark:border-gray-600'>
    <%= page_entries_info @products %>
  </div>
</div>